export default {
  products: [
    {
      _id: "1",
      name: "Slim Shirt",
      category: "Shirts",
      image: "/images/d1.jpg",
      price: 66,
      brand: "Nike",
      rating: 4.5,
      numReviews: 11,
      countInStock: 7,
    },
    {
      _id: "2",
      name: "Fit Shirt",
      category: "Shirts",
      image: "/images/f1.jpg",
      price: 35,
      brand: "Adidas",
      rating: 5.5,
      numReviews: 14,
      countInStock: 12,
    },
    {
      _id: "3",
      name: "Slim Pants",
      category: "Pants",
      image: "/images/s1.jpg",
      price: 40,
      brand: "Puma",
      rating: 4.0,
      numReviews: 19,
      countInStock: 3,
    },
    {
      _id: "4",
      name: "Slim Pants",
      category: "Pants",
      image: "/images/s1.jpg",
      price: 40,
      brand: "Puma",
      rating: 4.0,
      numReviews: 19,
      countInStock: 0,
    },
  ],
};
